---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -f *.php *.html *.shtml *.xml *.txt *.jpeg $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/posts/images
    - /bin/cp -f posts/*.php $DEPLOYPATH/posts/
    - /bin/cp -f posts/images/* $DEPLOYPATH/posts/images/
